version: '3'

services:
  emubuntu1604:
    build:
      context: ./ubuntu
    volumes:
      - ../:/var/www/html/eventm
    ports:
      - "8081:80"
      - "444:443"
  emmysql:
    image: mysql:5.7.24
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eventm
      MYSQL_USER: eventmu
      MYSQL_PASSWORD: eventmp
    ports:
      - "42334:3306"